title: 'LibreNav'
author:
  name: 'LibreNav.org'
  email: ''
description: >-
    ""

url: "https://librenav.org"

timezone: "Asia/Kolkata"
custom_head: true
subscribe: false

permalink: '/:categories/:title/'

  #logo: '/assets/img/site-logo'
  #profile_picture: "/assets/img/profile-picture.jpg"

# Social
#github: dyskun
#linkedin: dyskun
#twitter: dyskun

date_format: "%b %-d, %Y"

link-tags: true

theme: sencilla

exclude:
  - CHANGELOG.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

plugins:
 - jekyll-seo-tag
 - jekyll-sitemap

