title: 'LibreNav'
author:
  name: 'LibreNav.org'
  email: 'librenav[dot]org[∂]gmail[dot]com'
description: >-
    ""

url: "https://librenav.org"

timezone: "Asia/Kolkata"
custom_head: true
subscribe: false

permalink: '/:categories/:title/'

logo: '/assets/img/site-logo'
  #profile_picture: "/assets/img/site-logo"

# Social
github: https://github.com/msaharan/librenav
# linkedin: 
# twitter: 
bluesky: https://bsky.app/profile/librenav.org 

date_format: "%b %-d, %Y"

link-tags: true

theme: sencilla

exclude:
  - CHANGELOG.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

plugins:
 - jekyll-seo-tag
 - jekyll-sitemap

